version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=sigma2025!
      - PG_DATABASE=netflix
      - PG_HOST=db
      - PG_PORT=5433
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: netflix
    ports:
      - "5433:5432"
